# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        tar xvfz ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure
        make
        sudo make install     
        pip install TA-Lib
  build-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@master
#       - name: Publish to Registry
#         uses: elgohr/Publish-Docker-Github-Action@master
#         with:
#           name: myDocker/repository
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}    
        - name: Check out the repo
          uses: actions/checkout@v2
        -
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
        - name: Build and push image to the Docker Hub
          uses: docker/build-push-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
            dockerfile: Dockerfile
            tag_with_ref: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref
            tag_with_sha: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha
            tags: latest
        
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       -
#         name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v4
        
#         with:
#           file: Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/register:latest
#       -
#         name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
        
        
#     - name: Run Python
#       run: |
#         python3 assignment_230411.py
